[build]
buildCommand = "pnpm config set \"//npm.pkg.github.com/:_authToken\" \"$NODE_AUTH_TOKEN\" && turbo run build --filter=@cypress-ink-labs/web"

[deploy]
startCommand = "pnpm --filter=@cypress-ink-labs/web start"
healthcheckPath = "/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
