// NOTE: These specs require a live Supabase instance and PLAYWRIGHT_ADMIN_* creds.
// They are best-effort and unverified by the author — run them in a real environment only.

import { expect, test } from "@playwright/test"

// Uses the admin storageState set up by auth.setup.ts (inherited from playwright.config.ts)

test.describe("submit event (auth-gated)", () => {
  test("submit-event form is reachable and renders key fields", async ({ page }) => {
    // Try common submit / suggest paths
    await page.goto("/submit", { waitUntil: "domcontentloaded" })

    // If the route redirects to sign-in we are not properly authenticated
    const url = page.url()
    if (url.includes("/sign-in")) {
      test.skip()
      return
    }

    // Wait for some form element
    const form = page.getByRole("form").first()
    const hasForm = await form
      .waitFor({ state: "visible", timeout: 15_000 })
      .then(() => true)
      .catch(() => false)

    if (!hasForm) {
      // Try alternate path
      await page.goto("/events/submit", { waitUntil: "domcontentloaded" })
    }

    await expect(page.getByRole("textbox").first()).toBeVisible({ timeout: 15_000 })
  })

  test("submit form can be opened from explore page", async ({ page }) => {
    await page.goto("/explore", { waitUntil: "domcontentloaded" })
    await expect(page.getByRole("heading", { name: /today's adventures/i })).toBeVisible({
      timeout: 15_000,
    })

    // Look for a submit / suggest / add event button
    const submitButton = page.getByRole("button", {
      name: /submit|suggest|add event|new event/i,
    })
    const submitLink = page.getByRole("link", { name: /submit|suggest|add event|new event/i })

    const hasSubmitButton = (await submitButton.count()) > 0
    const hasSubmitLink = (await submitLink.count()) > 0

    if (!hasSubmitButton && !hasSubmitLink) {
      test.info().annotations.push({
        type: "note",
        description: "No submit/suggest button on explore — may be accessible elsewhere",
      })
      test.skip()
      return
    }

    if (hasSubmitButton) {
      await submitButton.first().click()
    } else {
      await submitLink.first().click()
    }

    // Expect a form or modal to appear
    await expect(page.getByRole("textbox").first()).toBeVisible({ timeout: 15_000 })
  })

  test("submit form requires title field and shows validation on empty submit", async ({
    page,
  }) => {
    await page.goto("/submit", { waitUntil: "domcontentloaded" })

    if (page.url().includes("/sign-in")) {
      test.skip()
      return
    }

    const titleField = page.getByRole("textbox", { name: /title|name|event name/i }).first()
    const hasTitleField = await titleField
      .waitFor({ state: "visible", timeout: 15_000 })
      .then(() => true)
      .catch(() => false)

    if (!hasTitleField) {
      test.skip()
      return
    }

    // Submit without filling — should show validation errors
    const submitButton = page.getByRole("button", { name: /submit|save|create/i }).first()
    await submitButton.click()

    // Expect some validation feedback
    await expect(
      page.getByText(/required|cannot be empty|please (enter|fill|provide)/i)
    ).toBeVisible({ timeout: 10_000 })
  })

  test("submit form: fill title and description, then submit (gated — may need admin)", async ({
    page,
  }) => {
    await page.goto("/submit", { waitUntil: "domcontentloaded" })

    if (page.url().includes("/sign-in")) {
      test.skip()
      return
    }

    const titleField = page.getByRole("textbox", { name: /title|name|event name/i }).first()
    const hasTitleField = await titleField
      .waitFor({ state: "visible", timeout: 15_000 })
      .then(() => true)
      .catch(() => false)

    if (!hasTitleField) {
      test.skip()
      return
    }

    await titleField.fill("E2E Test Event — please delete")

    const descField = page
      .getByRole("textbox", { name: /description|details|about/i })
      .first()
    if ((await descField.count()) > 0) {
      await descField.fill("Auto-generated by e2e tests — please delete")
    }

    const submitButton = page.getByRole("button", { name: /submit|save|create/i }).first()
    await submitButton.click()

    // Either success confirmation or redirect to the new event
    await expect(
      page
        .getByText(/submitted|saved|created|success|thank you/i)
        .or(page.getByRole("heading", { level: 1 }))
    ).toBeVisible({ timeout: 30_000 })
  })
})
