name: renovate

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - main
    paths:
      - renovate.json
  workflow_dispatch:

concurrency:
  group: renovate
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Renovate
        uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd # v46.1.15
        with:
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
        env:
          NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
